### ISSUE TITLE
'its' for expecting exceptions

### ISSUE THREAD

**Issue by islandsvinur** [rspec/rspec-its#24]
I was trying to use 'its' syntax for expecting exceptions:

```ruby
 4: class Subject
 5:   def some_method
 6:     raise Exception
 7:   end
 8: end
 9: 
10: describe Subject do
11:     it { expect { subject.some_method }.to raise_error Exception }
12:     its(:some_method) { is_expected.to raise_error Exception }
13:     its(:some_method) { should raise_error Exception }
14: end
```

I expected all three tests to succeed, however:

```
.FF

Failures:

  1) Subject some_method
     Failure/Error: raise Exception
     Exception:
       Exception
     # ./exception.rb:6:in `some_method'
     # ./exception.rb:12:in `block (2 levels) in <top (required)>'

  2) Subject some_method
     Failure/Error: raise Exception
     Exception:
       Exception
     # ./exception.rb:6:in `some_method'
     # ./exception.rb:13:in `block (2 levels) in <top (required)>'

Finished in 0.0014 seconds (files took 0.07659 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./exception.rb:12 # Subject some_method
rspec ./exception.rb:13 # Subject some_method
```

**Comment by islandsvinur** [comment]
I understand and tend to agree with your reasoning that ```its``` is only meant for attribute values and thus does not need exception testing.

Feel free to close this issue; the alternative (or actually the original) is just as good.
